chore: merge gasp-avs e2e test moon tasks with the main e2e tests matrix

diff --git a/.github/workflows/reusable-e2e-tests.yml b/.github/workflows/reusable-e2e-tests.yml
--- a/.github/workflows/reusable-e2e-tests.yml
+++ b/.github/workflows/reusable-e2e-tests.yml
@@ -42,75 +42,75 @@ env:
   CACHE_VERSION: 1
 
 jobs:
-  run-avs-tests:
-    runs-on: ubuntu-24.04
-    strategy:
-      matrix:
-        test:
-          - command: "moon gasp-avs:e2e-test-opt-out"
-            name: "test-opt-out"
-          - command: "moon gasp-avs:e2e-test-corrupted"
-            name: "test-corrupted"
-    env:
-      MOON_TOOLCHAIN_FORCE_GLOBALS: node,yarn
-      IMAGE_TAG: ${{ inputs.globalVersion }}
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-          submodules: false
-      - name: Cache Git submodules
-        if: inputs.cacheEnabled == true
-        uses: actions/cache@v4
-        id: cache
-        with:
-          path: |
-            .git/modules
-          key: submodules-${{ env.CACHE_VERSION }}-${{ hashFiles('.gitmodules') }}-${{ github.sha }}
-          restore-keys: |
-            submodules-${{ env.CACHE_VERSION }}-${{ hashFiles('.gitmodules') }}-
-            submodules-${{ env.CACHE_VERSION }}-
-      - run: |
-          git config --global url."https://github.com/".insteadOf "git@github.com:"
-          git submodule update --init --recursive --depth 1
+  # run-avs-tests:
+  #   runs-on: ubuntu-24.04
+  #   strategy:
+  #     matrix:
+  #       test:
+  #         - command: "moon gasp-avs:e2e-test-opt-out"
+  #           name: "test-opt-out"
+  #         - command: "moon gasp-avs:e2e-test-corrupted"
+  #           name: "test-corrupted"
+  #   env:
+  #     MOON_TOOLCHAIN_FORCE_GLOBALS: node,yarn
+  #     IMAGE_TAG: ${{ inputs.globalVersion }}
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #         submodules: false
+  #     - name: Cache Git submodules
+  #       if: inputs.cacheEnabled == true
+  #       uses: actions/cache@v4
+  #       id: cache
+  #       with:
+  #         path: |
+  #           .git/modules
+  #         key: submodules-${{ env.CACHE_VERSION }}-${{ hashFiles('.gitmodules') }}-${{ github.sha }}
+  #         restore-keys: |
+  #           submodules-${{ env.CACHE_VERSION }}-${{ hashFiles('.gitmodules') }}-
+  #           submodules-${{ env.CACHE_VERSION }}-
+  #     - run: |
+  #         git config --global url."https://github.com/".insteadOf "git@github.com:"
+  #         git submodule update --init --recursive --depth 1
 
-      - name: Install Foundry
-        uses: foundry-rs/foundry-toolchain@v1
-        with:
-          cache: ${{ inputs.cacheEnabled }}
-      - name: build and copy contracts
-        working-directory: contracts
-        run: forge build
+  #     - name: Install Foundry
+  #       uses: foundry-rs/foundry-toolchain@v1
+  #       with:
+  #         cache: ${{ inputs.cacheEnabled }}
+  #     - name: build and copy contracts
+  #       working-directory: contracts
+  #       run: forge build
 
-      - uses: moonrepo/setup-toolchain@v0.4.1
-        with:
-          cache-version: ${{ env.CACHE_VERSION }}
-          cache: ${{ inputs.cacheEnabled }}
+  #     - uses: moonrepo/setup-toolchain@v0.4.1
+  #       with:
+  #         cache-version: ${{ env.CACHE_VERSION }}
+  #         cache: ${{ inputs.cacheEnabled }}
       
-      - run: corepack enable && corepack prepare yarn@4.7.0 --activate
-      - uses: actions/setup-node@v4
-        with:
-          node-version-file: ./gasp-avs/.nvmrc
-          cache: ${{ inputs.cacheEnabled && 'yarn' || '' }}
-          cache-dependency-path: './gasp-avs/tests/yarn.lock'
-      - run: cd gasp-avs/tests && yarn install
+  #     - run: corepack enable && corepack prepare yarn@4.7.0 --activate
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version-file: ./gasp-avs/.nvmrc
+  #         cache: ${{ inputs.cacheEnabled && 'yarn' || '' }}
+  #         cache-dependency-path: './gasp-avs/tests/yarn.lock'
+  #     - run: cd gasp-avs/tests && yarn install
 
-      - name: Run test command "${{ matrix.test.command }}"
-        run: ${{ matrix.test.command }}
+  #     - name: Run test command "${{ matrix.test.command }}"
+  #       run: ${{ matrix.test.command }}
 
-      - name: Show Docker Compose logs in case of failure
-        if: failure()
-        run: cat $GITHUB_WORKSPACE/tmp/logs/*.txt
+  #     - name: Show Docker Compose logs in case of failure
+  #       if: failure()
+  #       run: cat $GITHUB_WORKSPACE/tmp/logs/*.txt
 
-      - name: Upload logs as an artifact on failure
-        if: failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ matrix.test.name }}-logs
-          path: tmp/logs/
+  #     - name: Upload logs as an artifact on failure
+  #       if: failure()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: ${{ matrix.test.name }}-logs
+  #         path: tmp/logs/
 
-      - uses: appthrust/moon-ci-retrospect@v1
-        if: success() || failure()
+  #     - uses: appthrust/moon-ci-retrospect@v1
+  #       if: success() || failure()
 
   ferry-withdrawal-test:
     name: Ferry withdrawal tests
