feat: enable updated test-rollup e2e tests process run

diff --git a/.github/workflows/reusable-e2e-tests.yml b/.github/workflows/reusable-e2e-tests.yml
--- a/.github/workflows/reusable-e2e-tests.yml
+++ b/.github/workflows/reusable-e2e-tests.yml
@@ -38,79 +38,79 @@ env:
   IMAGE_TAG: ${{ inputs.globalVersion }}
 
 jobs:
-  run-e2e-tests:
-    runs-on: ubuntu-24.04
+  # run-e2e-tests:
+  #   runs-on: ubuntu-24.04
 
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          submodules: recursive
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         submodules: recursive
 
-      - name: Start env
-        run: docker compose up -d
+  #     - name: Start env
+  #       run: docker compose up -d
 
-      - name: Use custom branch in e2e tests repository if it exists, otherwise use default branch
-        id: e2e
-        run: |
-          # Implementation of this conditional action was taken from here:
-          # https://github.com/actions/checkout/issues/512#issuecomment-1264735491
+  #     - name: Use custom branch in e2e tests repository if it exists, otherwise use default branch
+  #       id: e2e
+  #       run: |
+  #         # Implementation of this conditional action was taken from here:
+  #         # https://github.com/actions/checkout/issues/512#issuecomment-1264735491
 
-          # This condition check if the input 'e2eBranch' is empty, and if it is, it checks if the current branch name exists in 'mangata-e2e' repository
-          if [[ -z "${{ inputs.e2eBranch }}" ]]; then
-            # Checking if current branch name exists in 'mangata-e2e' repository
-            if git ls-remote --heads --quiet --exit-code https://github.com/mangata-finance/mangata-e2e.git ${{ env.CURRENT_BRANCH }}; then
-              echo "Using custom '${{ env.CURRENT_BRANCH }}' branch as it exists in 'mangata-e2e' repository"
-              echo "BRANCH=${{ env.CURRENT_BRANCH }}" >> $GITHUB_OUTPUT
-            else
-              echo "Custom branch '${{ env.CURRENT_BRANCH }}' does not exist in 'mangata-e2e' repository, using default '${{ env.DEFAULT_E2E_REPO_BRANCH }}' branch"
-              echo "BRANCH=${{ env.DEFAULT_E2E_REPO_BRANCH }}" >> $GITHUB_OUTPUT
-            fi
-          else
-            echo "Using '${{ inputs.e2eBranch }}' branch fo 'mangata-e2e' repository as it was provided in the input"
-            echo "BRANCH=${{ inputs.e2eBranch }}" >> $GITHUB_OUTPUT
-          fi
+  #         # This condition check if the input 'e2eBranch' is empty, and if it is, it checks if the current branch name exists in 'mangata-e2e' repository
+  #         if [[ -z "${{ inputs.e2eBranch }}" ]]; then
+  #           # Checking if current branch name exists in 'mangata-e2e' repository
+  #           if git ls-remote --heads --quiet --exit-code https://github.com/mangata-finance/mangata-e2e.git ${{ env.CURRENT_BRANCH }}; then
+  #             echo "Using custom '${{ env.CURRENT_BRANCH }}' branch as it exists in 'mangata-e2e' repository"
+  #             echo "BRANCH=${{ env.CURRENT_BRANCH }}" >> $GITHUB_OUTPUT
+  #           else
+  #             echo "Custom branch '${{ env.CURRENT_BRANCH }}' does not exist in 'mangata-e2e' repository, using default '${{ env.DEFAULT_E2E_REPO_BRANCH }}' branch"
+  #             echo "BRANCH=${{ env.DEFAULT_E2E_REPO_BRANCH }}" >> $GITHUB_OUTPUT
+  #           fi
+  #         else
+  #           echo "Using '${{ inputs.e2eBranch }}' branch fo 'mangata-e2e' repository as it was provided in the input"
+  #           echo "BRANCH=${{ inputs.e2eBranch }}" >> $GITHUB_OUTPUT
+  #         fi
 
-      - name: Checkout tests
-        uses: actions/checkout@v4
-        with:
-          repository: mangata-finance/mangata-e2e
-          ref: ${{ steps.e2e.outputs.BRANCH }}
-          path: e2eTests
+  #     - name: Checkout tests
+  #       uses: actions/checkout@v4
+  #       with:
+  #         repository: mangata-finance/mangata-e2e
+  #         ref: ${{ steps.e2e.outputs.BRANCH }}
+  #         path: e2eTests
 
-      - name: Install e2e tests dependencies
-        working-directory: e2eTests
-        run: yarn install
+  #     - name: Install e2e tests dependencies
+  #       working-directory: e2eTests
+  #       run: yarn install
 
-      - name: Docker ps
-        run: docker ps --no-trunc
+  #     - name: Docker ps
+  #       run: docker ps --no-trunc
 
-      - name: Run tests
-        working-directory: e2eTests
-        run: yarn test-rollup
+  #     - name: Run tests
+  #       working-directory: e2eTests
+  #       run: yarn test-rollup
 
-      - name: Get sequencer logs
-        if: success() || failure()
-        run: docker logs rollup-sequencer-eth-1
-      - name: Get aggregator logs
-        if: success() || failure()
-        run: docker logs rollup-avs-aggregator-1
-      - name: Get gasp-avs logs
-        if: success() || failure()
-        run: docker logs rollup-gasp-avs-1
-      - name: Get updater-arb logs
-        if: success() || failure()
-        run: docker logs rollup-updater-arb-1
-      - name: Get node logs
-        if: success() || failure()
-        run: docker logs rollup-node-alice-1
+  #     - name: Get sequencer logs
+  #       if: success() || failure()
+  #       run: docker logs rollup-sequencer-eth-1
+  #     - name: Get aggregator logs
+  #       if: success() || failure()
+  #       run: docker logs rollup-avs-aggregator-1
+  #     - name: Get gasp-avs logs
+  #       if: success() || failure()
+  #       run: docker logs rollup-gasp-avs-1
+  #     - name: Get updater-arb logs
+  #       if: success() || failure()
+  #       run: docker logs rollup-updater-arb-1
+  #     - name: Get node logs
+  #       if: success() || failure()
+  #       run: docker logs rollup-node-alice-1
 
-      - name: Test Report
-        uses: dorny/test-reporter@v1.8.0
-        if: success() || failure()
-        with:
-          name: E2E report test-rollup
-          path: e2eTests/reports/*.xml
-          reporter: jest-junit
+  #     - name: Test Report
+  #       uses: dorny/test-reporter@v1.8.0
+  #       if: success() || failure()
+  #       with:
+  #         name: E2E report test-rollup
+  #         path: e2eTests/reports/*.xml
+  #         reporter: jest-junit
 
   run-avs-tests:
     runs-on: ubuntu-24.04
