chore(ci): update the image references used in e2e tests for gasp-avs and gasp-node services to use the correct reference when running tests (#535)

diff --git a/gasp-avs/moon.yml b/gasp-avs/moon.yml
--- a/gasp-avs/moon.yml
+++ b/gasp-avs/moon.yml
@@ -43,7 +43,7 @@ tasks:
     outputs: ['target/release/main']
 
   build-image-local:
-    command: 'docker buildx build --build-arg ROLLUP_NODE_VERSION=local -t gaspxyz/gasp-avs:local --load .'
+    command: 'docker buildx build --build-arg ROLLUP_NODE_VERSION=local -t ${DOCKERHUB_REPOSITORY}:local --load .'
     options:
       envFile: '/.env'
     deps: ['gasp-node:build-image-local']
@@ -58,7 +58,7 @@ tasks:
         --cache-to type=registry,ref=${IMAGE_BUILD_REPOSITORY}:buildcache-standard-runtime,mode=max \
         --output type=image,push=true,push-by-digest=true,name=${IMAGE_BUILD_REPOSITORY} \
         --build-arg ROLLUP_NODE_REPOSITORY=${IMAGE_BUILD_ROLLUP_NODE_REPOSITORY} \
-        --build-arg ROLLUP_NODE_VERSION=${IMAGE_TAG:-ci} \
+        --build-arg ROLLUP_NODE_VERSION=${IMAGE_TAG} \
         --metadata-file gasp-avs-standard-runtime-buildkit-metadata.json -f Dockerfile ./
       
       BUILD_EXIT_CODE=$?
@@ -97,7 +97,7 @@ tasks:
         --cache-to type=registry,ref=${IMAGE_BUILD_REPOSITORY}:buildcache-fast-runtime,mode=max \
         --output type=image,push=true,push-by-digest=true,name=${IMAGE_BUILD_REPOSITORY} \
         --build-arg ROLLUP_NODE_REPOSITORY=${IMAGE_BUILD_ROLLUP_NODE_REPOSITORY} \
-        --build-arg ROLLUP_NODE_VERSION=${IMAGE_TAG:-ci}-fast \
+        --build-arg ROLLUP_NODE_VERSION=${IMAGE_TAG}-fast \
         --metadata-file gasp-avs-fast-runtime-buildkit-metadata.json -f Dockerfile ./
       
       BUILD_EXIT_CODE=$?
@@ -134,18 +134,18 @@ tasks:
       IMAGE_DIGEST_FAST_RUNTIME=$(jq -r '."containerimage.digest"' gasp-avs-fast-runtime-buildkit-metadata.json)
 
       docker buildx imagetools create \
-        --tag ${IMAGE_BUILD_REPOSITORY}:${IMAGE_TAG:-ci} \
-        --tag ${DOCKERHUB_REPOSITORY}:${IMAGE_TAG:-ci} \
+        --tag ${IMAGE_BUILD_REPOSITORY}:${IMAGE_TAG} \
+        --tag ${DOCKERHUB_REPOSITORY}:${IMAGE_TAG} \
         ${IMAGE_BUILD_REPOSITORY}@${IMAGE_DIGEST_STANDARD_RUNTIME}
 
-      echo "Successfully created ${IMAGE_BUILD_REPOSITORY}:${IMAGE_TAG:-ci} from existing digests"
+      echo "Successfully created ${IMAGE_BUILD_REPOSITORY}:${IMAGE_TAG} from existing digests"
 
       docker buildx imagetools create \
-        --tag ${IMAGE_BUILD_REPOSITORY}:${IMAGE_TAG:-ci}-fast \
-        --tag ${DOCKERHUB_REPOSITORY}:${IMAGE_TAG:-ci}-fast \
+        --tag ${IMAGE_BUILD_REPOSITORY}:${IMAGE_TAG}-fast \
+        --tag ${DOCKERHUB_REPOSITORY}:${IMAGE_TAG}-fast \
         ${IMAGE_BUILD_REPOSITORY}@${IMAGE_DIGEST_FAST_RUNTIME}
 
-      echo "Successfully created ${IMAGE_BUILD_REPOSITORY}:${IMAGE_TAG:-ci}-fast from existing digests"
+      echo "Successfully created ${IMAGE_BUILD_REPOSITORY}:${IMAGE_TAG}-fast from existing digests"
     deps: 
       # - gasp-node:build-image-ci
       - buildkit-build-and-push-image-digests-standard-runtime
@@ -177,14 +177,16 @@ tasks:
 
   e2e-test-opt-out:
     script: |
-      export ROLLUP_NODE_VERSION=${IMAGE_TAG:-ci}-fast
-      export GASP_AVS_VERSION=${IMAGE_TAG:-ci}-fast
-      export GASP_CONTRACTS_VERSION=${IMAGE_TAG:-ci}
-      export AVS_AGGREGATOR_VERSION=${IMAGE_TAG:-ci}
-      export FERRY_WITHDRAWAL_VERSION=${IMAGE_TAG:-ci}
-      export FERRY_DEPOSIT_VERSION=${IMAGE_TAG:-ci}
-      export ROLLUP_SEQUENCER_VERSION=${IMAGE_TAG:-ci}
-      export UPDATER_VERSION=${IMAGE_TAG:-ci}
+      # set -e  # Exit immediately if a command exits with a non-zero status
+      
+      export ROLLUP_NODE_VERSION=${IMAGE_TAG:-local}-fast
+      export GASP_AVS_VERSION=${IMAGE_TAG:-local}-fast
+      export GASP_CONTRACTS_VERSION=${IMAGE_TAG:-local}
+      export AVS_AGGREGATOR_VERSION=${IMAGE_TAG:-local}
+      export FERRY_WITHDRAWAL_VERSION=${IMAGE_TAG:-local}
+      export FERRY_DEPOSIT_VERSION=${IMAGE_TAG:-local}
+      export ROLLUP_SEQUENCER_VERSION=${IMAGE_TAG:-local}
+      export UPDATER_VERSION=${IMAGE_TAG:-local}
 
       docker compose down && docker compose up -d
 
@@ -205,14 +207,14 @@ tasks:
   
   e2e-test-corrupted:
     script: |
-      export ROLLUP_NODE_VERSION=${IMAGE_TAG:-ci}-fast
-      export GASP_AVS_VERSION=${IMAGE_TAG:-ci}-fast
-      export GASP_CONTRACTS_VERSION=${IMAGE_TAG:-ci}
-      export AVS_AGGREGATOR_VERSION=${IMAGE_TAG:-ci}
-      export FERRY_WITHDRAWAL_VERSION=${IMAGE_TAG:-ci}
-      export FERRY_DEPOSIT_VERSION=${IMAGE_TAG:-ci}
-      export ROLLUP_SEQUENCER_VERSION=${IMAGE_TAG:-ci}
-      export UPDATER_VERSION=${IMAGE_TAG:-ci}
+      export ROLLUP_NODE_VERSION=${IMAGE_TAG:-local}-fast
+      export GASP_AVS_VERSION=${IMAGE_TAG:-local}-fast
+      export GASP_CONTRACTS_VERSION=${IMAGE_TAG:-local}
+      export AVS_AGGREGATOR_VERSION=${IMAGE_TAG:-local}
+      export FERRY_WITHDRAWAL_VERSION=${IMAGE_TAG:-local}
+      export FERRY_DEPOSIT_VERSION=${IMAGE_TAG:-local}
+      export ROLLUP_SEQUENCER_VERSION=${IMAGE_TAG:-local}
+      export UPDATER_VERSION=${IMAGE_TAG:-local}
       
       docker compose down && docker compose up -d
 
